### ISSUE TITLE
Music stops playing after loading error

### ISSUE THREAD

**Issue by AndrewSologor** [ryanio/focusmusic.fm#1]
Sometimes "error loading :(" message appears and music stops playing. After I click "Next" next composition starts playing but error message still remains on the page. How about just automatically switch to the next audio file and don't show this error message to the user?

**Comment by ryanio** [comment]
Thanks Andrew! Didn't think about clearing the error message.

I don't think I'll implement automatically switching to the next track for now since the error could be for various reasons (e.g. internet cuts out) so I'll let the user re-initiate pressing play or next.
