### ISSUE TITLE
Feature Request: allow musicians to showcase their work

### ISSUE THREAD

**Issue by StewAlexander-com** [ryanio/focusmusic.fm#10]
Maybe add a link for artists to get in touch with you to showcase their music?

Plenty of great stuff out there, but you could get some artists to feed you music because they want the exposure.

Just a thought, don't want to muddy the experience for users, just looking at ways to get you more music

**Comment by StewAlexander-com** [comment]
@ryanio - hey man, love your app but are you paying attention to issues?

**Comment by ryanio** [comment]
There is a message on the Donate page: `We are also always looking for new music. If you are an artist, please get in touch ryan@focusmusic.fm`
