### ISSUE TITLE
[REQUEST] Firefox plug-in to control

### ISSUE THREAD

**Issue by ShinobiWPS** [ryanio/focusmusic.fm#12]
First of all

Focus Music is awesome, thank you for your work!

Second: as the title says: is it possible to make one?

**Comment by ryanio** [comment]
Hey Shinobi, that would be great. I'm not familiar with creating browser extensions but if you want to give it a shot I can give you an outline of how the backend API works, or you can read the [javascript file](https://github.com/ryanio/focusmusic.fm/blob/master/static/js/app.js).

Best,
Ryan

**Comment by ShinobiWPS** [comment]
Holy cow! I could be the first to do it,yeah why not, i've just decided to make it.

**Comment by ShinobiWPS** [comment]
Can you send me an outline of the APIs?

**Comment by ryanio** [comment]
Hey, yes for sure, thanks for jumping into it, I'm excited to see what you come up with!

I think the best way is to read and follow https://github.com/ryanio/focusmusic.fm/blob/master/static/js/app.js and let me know if you have any questions.

Best,
Ryan

**Comment by StewAlexander-com** [comment]
Any updates? I'm following this ...

**Comment by ShinobiWPS** [comment]
nope, not even started yet, other ossue in my personal life blocked me to do so ,so far

**Comment by StewAlexander-com** [comment]
@ryanio @ShinobiWPS  - since there is no time table, probably want to close this until it can be re-tabled as a to-do

**Comment by ShinobiWPS** [comment]
agree

**Comment by ryanio** [comment]
Thanks guys
