### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by oneminch** [ryanio/focusmusic.fm#13]
I'm looking to improve some of the front end design for focusmusic.fm. I'm sort of a beginner in the open source world and I'm making my first steps to contribute. What are your thoughts on making some design imrovements?

**Comment by ryanio** [comment]
Hey, sure, I'm always open to ideas :) Feel free to make a Pull Request with your changes in this repository and I can review them.

Best,
Ryan

**Comment by oneminch** [comment]
Hey, it turns out I opened this issue at a bad time. I will close it and re-open it in the near future when I'm likely have less on plate. Or I'll just make my edit and submit a pull request if that's okay. Thanks!
