### ISSUE TITLE
You could be the next Tim Westergren  (founder of Pandora)

### ISSUE THREAD

**Issue by StewAlexander-com** [ryanio/focusmusic.fm#18]
@ryanio 

Not sure how much of this you know ...

Many years ago (oh close to 20 now), Pandora was more or less a free music service backed by this algorithm Tim helped build called the Music Genome Product (now essentially copied and used in Apple Music, and Spotify and etc etc)

Then licensing fees almost killed Pandora, Tim went on a campaign getting many of the earlier adopters  to sign petitions arguing for the rights to play music.

This lead to the "pay to play" model most music streamers (save your site and a very few others) now use. 

I'm happy to support your "open source" music streamer, think its awesome.

Thank you for making a great product.

Feel free to close this, just wanted to write a little spam -- Pandora by the way is now a clear channel product (more or less) as it is owned by Sirius XM.

**Comment by ryanio** [comment]
Thanks!

**Comment by san-kumar** [comment]
I want to second this. Definitely an amazing project. So many thanks for making it. 

@ryanio You have an amazing taste in focus music!

Edit: P.S. I've found that if I open [something like this](https://www.youtube.com/watch?v=43IyXq4VwjM) another tab (at a very low volume so it's barely audible) it increases my focus even more. Could be very much placebo though :)
