### ISSUE TITLE
Error Loading

### ISSUE THREAD

**Issue by FiZiX** [ryanio/focusmusic.fm#4]
Recently I've been getting an "error loading :(" message when focusmusic attempts to load the next song. Here is the error that appears in the console:

`(index):1 GET https://focusmusic.fm/static/tracks/fresh-code-destiny-club-mix.mp3 net::ERR_CONTENT_LENGTH_MISMATCH`

**Comment by ryanio** [comment]
Hm is this still happening for you?

**Comment by FiZiX** [comment]
I regrettably haven't used the service for a while so I'm not sure. I'll close the ticket for now.
