### ISSUE TITLE
Shuffle feature request

### ISSUE THREAD

**Issue by tmugrage** [ryanio/focusmusic.fm#6]
It would be amazing to have a shuffle or play random feature.

**Comment by ryanio** [comment]
The backend does actually shuffle the tracks every time on page load. Let me know if you seem to be hearing the same songs in a row repeatedly.

Thanks,
Ryan

**Comment by tmugrage** [comment]
I am using Chrome. Everytime I start focusmusic (new browser session) track #1 is always the same. I will try the refresh.
