### ISSUE TITLE
Option to disable cross fade?

### ISSUE THREAD

**Issue by lolmaus** [ryanio/focusmusic.fm#8]
Cross fade makes music sound out of tune for a few seconds, every few minutes.

Very disturbing.

PS Thank you for the awesome service, I've sent you a humble donation.

**Comment by ryanio** [comment]
Thanks so much. Hm I don't think I have implemented any cross-fade feature. I'm not sure why that would be happening for you.

**Comment by lolmaus** [comment]
Could it be a default of the audio library you're using?

Cross fade means that the next track starts a few second before the current track finishes. So for a few seconds they sound both at the same time.

**Comment by lolmaus** [comment]
I may be imagining it... But I swear I'm hearing it often. :)

**Comment by ryanio** [comment]
It might be just you hehe, here is the code - audiojs calls `trackEnded` after the end of the currently playing track: https://github.com/ryanio/focusmusic.fm/blob/master/static/js/app.js#L61

**Comment by lolmaus** [comment]
Thx!

Maybe some tracks are designed to sound out of tune...

**Comment by lolmaus** [comment]
Ha!

Turns out, many tracks are *mixes*: multiple tracks assembled into a single track. And they have crossfade inside them!

For example, listen to [this track](https://soundcloud.com/traffic/its-all-good-mix-downtempo) between 53:30 and 54:20. Very annoying! 😅
